"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 14:32:00.258998
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emisores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=2), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=80), nullable=True),
    sa.Column('codigo_actividad', sa.String(length=6), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('telefono_codigo_pais', sa.String(length=3), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('provincia', sa.String(length=1), nullable=False),
    sa.Column('canton', sa.String(length=2), nullable=False),
    sa.Column('distrito', sa.String(length=2), nullable=False),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('otras_senas', sa.String(length=250), nullable=False),
    sa.Column('proveedor_sistemas', sa.String(length=20), nullable=True),
    sa.Column('ambiente', sa.String(length=4), nullable=False),
    sa.Column('hacienda_usuario', sa.String(length=100), nullable=True),
    sa.Column('hacienda_password_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('cert_p12_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('cert_password_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('cert_sujeto', sa.String(length=300), nullable=True),
    sa.Column('cert_vence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_identificacion')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('prefijo', sa.String(length=12), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_api_keys_emisor_id'), 'api_keys', ['emisor_id'], unique=False)
    op.create_table('consecutivos',
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sucursal', sa.Integer(), nullable=False),
    sa.Column('terminal', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('ultimo', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emisor_id', 'sucursal', 'terminal', 'tipo_documento')
    )
    op.create_table('documentos_recibidos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proveedor_tipo_identificacion', sa.String(length=2), nullable=True),
    sa.Column('proveedor_identificacion', sa.String(length=20), nullable=False),
    sa.Column('proveedor_nombre', sa.String(length=200), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('total_impuesto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_comprobante', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('firma_valida', sa.Boolean(), nullable=True),
    sa.Column('xml_original', sa.Text(), nullable=False),
    sa.Column('xml_respuesta_proveedor', sa.Text(), nullable=True),
    sa.Column('mensaje', sa.String(length=1), nullable=True),
    sa.Column('detalle_mensaje', sa.String(length=160), nullable=True),
    sa.Column('codigo_actividad', sa.String(length=6), nullable=True),
    sa.Column('condicion_impuesto', sa.String(length=2), nullable=True),
    sa.Column('monto_impuesto_acreditar', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('monto_gasto_aplicable', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('consecutivo_receptor', sa.String(length=20), nullable=True),
    sa.Column('fecha_mensaje', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xml_firmado', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ERROR_COMUNICACION', 'CONTINGENCIA', name='estadofactura'), nullable=True),
    sa.Column('estado_hacienda', sa.String(length=100), nullable=True),
    sa.Column('mensaje_hacienda', sa.Text(), nullable=True),
    sa.Column('envio_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clave_consulta', sa.String(length=71), nullable=True),
    sa.Column('intentos_envio', sa.Integer(), nullable=False),
    sa.Column('ultimo_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xml_respuesta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emisor_id', 'clave', name='uq_recibido_emisor_clave')
    )
    op.create_index(op.f('ix_documentos_recibidos_clave'), 'documentos_recibidos', ['clave'], unique=False)
    op.create_index(op.f('ix_documentos_recibidos_clave_consulta'), 'documentos_recibidos', ['clave_consulta'], unique=False)
    op.create_index(op.f('ix_documentos_recibidos_emisor_id'), 'documentos_recibidos', ['emisor_id'], unique=False)
    op.create_index(op.f('ix_documentos_recibidos_estado'), 'documentos_recibidos', ['estado'], unique=False)
    op.create_index(op.f('ix_documentos_recibidos_fecha_emision'), 'documentos_recibidos', ['fecha_emision'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('numero_consecutivo', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.Column('factura_origen_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('receptor_nombre', sa.String(length=200), nullable=True),
    sa.Column('receptor_identificacion', sa.String(length=20), nullable=True),
    sa.Column('receptor_tipo_identificacion', sa.String(length=2), nullable=True),
    sa.Column('receptor_correo', sa.String(length=160), nullable=True),
    sa.Column('condicion_venta', sa.String(length=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('total_venta', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_descuentos', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_gravado', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_exento', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_exonerado', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_otros_cargos', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('monto_impuesto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ERROR_COMUNICACION', 'CONTINGENCIA', name='estadofactura'), nullable=False),
    sa.Column('estado_hacienda', sa.String(length=100), nullable=True),
    sa.Column('mensaje_hacienda', sa.Text(), nullable=True),
    sa.Column('envio_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clave_consulta', sa.String(length=71), nullable=True),
    sa.Column('intentos_envio', sa.Integer(), nullable=False),
    sa.Column('ultimo_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correo_enviado', sa.Boolean(), nullable=False),
    sa.Column('xml_firmado', sa.Text(), nullable=True),
    sa.Column('xml_respuesta', sa.Text(), nullable=True),
    sa.Column('json_original', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ),
    sa.ForeignKeyConstraint(['factura_origen_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emisor_id', 'referencia_externa', name='uq_factura_referencia_externa')
    )
    op.create_index(op.f('ix_facturas_clave'), 'facturas', ['clave'], unique=True)
    op.create_index(op.f('ix_facturas_created_at'), 'facturas', ['created_at'], unique=False)
    op.create_index(op.f('ix_facturas_emisor_id'), 'facturas', ['emisor_id'], unique=False)
    op.create_index(op.f('ix_facturas_estado'), 'facturas', ['estado'], unique=False)
    op.create_index(op.f('ix_facturas_fecha_emision'), 'facturas', ['fecha_emision'], unique=False)
    op.create_table('facturas_detalles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('factura_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('linea_numero', sa.Integer(), nullable=False),
    sa.Column('codigo_cabys', sa.String(length=13), nullable=True),
    sa.Column('codigo_producto', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unidad_medida', sa.String(length=15), nullable=True),
    sa.Column('es_servicio', sa.Boolean(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('codigo_tarifa_iva', sa.String(length=2), nullable=True),
    sa.Column('impuesto_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impuesto_monto', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('monto_exonerado', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('impuesto_neto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_detalles_factura_id'), 'facturas_detalles', ['factura_id'], unique=False)
    op.create_table('facturas_eventos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('factura_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('documento_recibido_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_recibido_id'], ['documentos_recibidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_eventos_documento_recibido_id'), 'facturas_eventos', ['documento_recibido_id'], unique=False)
    op.create_index(op.f('ix_facturas_eventos_factura_id'), 'facturas_eventos', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_eventos_factura_id'), table_name='facturas_eventos')
    op.drop_index(op.f('ix_facturas_eventos_documento_recibido_id'), table_name='facturas_eventos')
    op.drop_table('facturas_eventos')
    op.drop_index(op.f('ix_facturas_detalles_factura_id'), table_name='facturas_detalles')
    op.drop_table('facturas_detalles')
    op.drop_index(op.f('ix_facturas_fecha_emision'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_estado'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_emisor_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_created_at'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_clave'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_documentos_recibidos_fecha_emision'), table_name='documentos_recibidos')
    op.drop_index(op.f('ix_documentos_recibidos_estado'), table_name='documentos_recibidos')
    op.drop_index(op.f('ix_documentos_recibidos_emisor_id'), table_name='documentos_recibidos')
    op.drop_index(op.f('ix_documentos_recibidos_clave_consulta'), table_name='documentos_recibidos')
    op.drop_index(op.f('ix_documentos_recibidos_clave'), table_name='documentos_recibidos')
    op.drop_table('documentos_recibidos')
    op.drop_table('consecutivos')
    op.drop_index(op.f('ix_api_keys_emisor_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('emisores')
    sa.Enum(name='estadofactura').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
