"""venta por consumo

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 15:36:16.882161
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('documentos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('dias_vigencia', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquetes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('documentos', sa.Integer(), nullable=False),
    sa.Column('usados', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('vence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_created_at'), 'paquetes', ['created_at'], unique=False)
    op.create_index(op.f('ix_paquetes_emisor_id'), 'paquetes', ['emisor_id'], unique=False)
    op.create_table('consumos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emisor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paquete_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('referencia', sa.String(length=71), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('factura_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('documento_recibido_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_recibido_id'], ['documentos_recibidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    op.create_index(op.f('ix_consumos_created_at'), 'consumos', ['created_at'], unique=False)
    op.create_index(op.f('ix_consumos_emisor_id'), 'consumos', ['emisor_id'], unique=False)
    op.create_index(op.f('ix_consumos_paquete_id'), 'consumos', ['paquete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumos_paquete_id'), table_name='consumos')
    op.drop_index(op.f('ix_consumos_emisor_id'), table_name='consumos')
    op.drop_index(op.f('ix_consumos_created_at'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_index(op.f('ix_paquetes_emisor_id'), table_name='paquetes')
    op.drop_index(op.f('ix_paquetes_created_at'), table_name='paquetes')
    op.drop_table('paquetes')
    op.drop_table('planes')
    # ### end Alembic commands ###
